apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres-deployment
  template:
    metadata:
      labels:
        db: postgres-deployment
    spec:
      volumes:
        - name: pvc-postgresdb
          persistentVolumeClaim:
              claimName: pvc-postgresdb

      containers:
        - name: postgres-deployment
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: PGPORT
              value: '5432'
          volumeMounts:
            - name: pvc-postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
